### ISSUE TITLE
Chapters start of new page each

### ISSUE THREAD

**Issue by gamingflexer** [kodaman2/markdown-book#1]
Hey great work i want to ask how can generate a pdf and each chapter should be in the first page

Thanks!

**Comment by TheFern2** [comment]
Hi @gamingflexer I would try using the suggestions in this [so answer](https://stackoverflow.com/questions/16965490/pandoc-markdown-page-break) this script uses pandoc behind the scenes so any formatting that pandoc accepts will work fine.

Try any of the below in your documents at the end of each chapter. 
```
/newpage or /pagebreak
```

Also the script automatically prints to pdf as a default option. You only need to provide the -p option for the directory of your chapters.

**Comment by gamingflexer** [comment]
Thanks a lot that worked ! Currently working to create a automated GPT text book and this really helped me !

**Comment by TheFern2** [comment]
Noice! Glad to hear it worked.
