### ISSUE TITLE
How to fix no font found issue?

### ISSUE THREAD

**Issue by sylviachency** [kodaman2/markdown-book#2]
I encountered this warning msg in vscode extension:

stderr: [WARNING] Missing character: There is no 大 (U+5927) (U+5927) in font [lmroman12-bold]:mapping=tex- [WARNING] Missing character: There is no 语 (U+8BED) (U+8BED) in font [lmroman12-bold]:mapping=tex- [WARNING] Missing character: There is no 言 (U+8A00) (U+8A00) in font [lmroman12-bold]:mapping=tex- [WARNING] Missing character: There is no 模 (U+6A21) (U+6A21) in font [lmroman12-bold]:mapping=tex- [WARNING] Missing character: There is no 型 (U+578B) (U+578B) in font [lmroman12-bold]:mapping=tex- [WARNING] Missing character: There is no 基 (U+57FA) (U+57FA) in font [lmroman12-bold]:mapping=tex- [WARNING] Missing character: There is no 础 (U+7840) (U+7840) in font [lmroman12-bold]:mapping=tex- [WARNING] Missing character: There is no 大 (U+5927) (U+5927) in font [lmroman10-bold]:mapping=tex- [WARNING] Missing character: There is no 模 (U+6A21) (U+6A21) in font [lmroman10-bold]:mapping=tex- [WARNING] Missing character: There is no 型 (U+578B) (U+578B) in font [lmroman10-bold]:mapping=tex- [W...

**Comment by TheFern2** [comment]
Closing issue moved to https://github.com/TheFern2/vscode-gutenberg/issues/1
